### ISSUE TITLE
Figure 7 in the paper - local quality maps

### ISSUE THREAD

**Issue by danier97** [VQAssessment/ExplainableVQA#1]
Hi, 

Thank you very much for sharing the interesting work and I really enjoyed reading your paper!

Could you please elaborate on how you produced the local quality maps from the final features in Figure 7? In particular how is the map for each dimension (e.g. sharpness) generated from $f^{Final}_{V_t}$?

Thank you in advance for your help.

**Comment by GZHU-DVL** [comment]
Thank you very much for sharing the interesting work and I really enjoyed reading your paper!
When will the relevant data of the dataset Maxwell be released?
