### ISSUE TITLE
Open_clip import error

### ISSUE THREAD

**Issue by waveshen** [VQAssessment/ExplainableVQA#2]
Hi,
The idea of separate different type of feature is very delicate. I just pulled this project and during running of this demo 'python evaluate_one_video.py -v ./demo/17734.mp4 -f', there was an import error said 'File "/group/dphi_dmz/tianhaos/VQA/DOVER/dover/models/conv_backbone.py", line 7, in <module>
    from open_clip import CLIP3D
ImportError: cannot import name 'CLIP3D' from 'open_clip' (/group/dphi_dmz/tianhaos/VQA/open_clip/src/open_clip/__init__.py)'. Could you guys check if there is a name typo or open_clip version problem? THX

**Comment by teowu** [comment]
can comment out this line in `DOVER/dover/models/conv_backbone.py`~will help.

**Comment by waveshen** [comment]
It works! THX
