### ISSUE TITLE
Maxwell database

### ISSUE THREAD

**Issue by GZHU-DVL** [VQAssessment/ExplainableVQA#4]
Thank you very much for sharing the interesting work and I really enjoyed reading your paper!
When will the relevant data of the dataset Maxwell be released?

**Comment by teowu** [comment]
The Gdrive link is ready (the baidupan link is banned from Baidu, though I don't know why), please refer to this for downloading the videos.

**Comment by teowu** [comment]
Please see this link and download: https://drive.google.com/file/d/1qs7C5Nq_twIpJpP3HwpjT-Yf-51qZ7Nd/view?usp=sharing

**Comment by GZHU-DVL** [comment]
Thank you for providing the Gdrive link for downloading the Maxwell dataset videos. Could you please share information about where I can find the labels or annotations for this dataset? Your assistance with this would be greatly appreciated.

**Comment by teowu** [comment]
The labels are maxwell_val.csv and maxwell_train.csv in this repo.
